language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'

before_install:
  - composer self-update

install:
  - composer install
  - composer --working-dir=./tests install --prefer-source --no-interaction

script: cd ./tests && vendor/bin/phpspec run -v --format progress
