language: php
php:
  # - '5.4'
  # - '5.5'
  # - '5.6'
  - '7.0'

before_script:
  - cd tests
  - rm composer.lock

before_install:
  - composer self-update

install:
  - cd tests
  - composer install

script: cd tests && vendor/bin/phpspec run -v --format progress
