language: php
php:
  # - '5.4'
  # - '5.5'
  # - '5.6'
  - '7.0'

services:
  - redis-server

before_install:
  - composer self-update

install:
  - composer install
  - composer --working-dir=./tests install

script: cd ./tests && vendor/bin/phpspec run -v --format progress
